export const PASSWORD_HASH_ROUND = 12;

export const CUSTOM_ID_LENGTH = 10;
export const REQUEST_ID_LENGTH = 25;
export const CUSTOM_ID_CHARACTERS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const CUSTOM_ID_PREFIX = {
  ADMIN: 'ADM',
  USER: 'USR',
};

export const API_ACCESS_KEY_LENGTH = 20;

export const JWT_TOKEN_EXPIRE_TIME = '7d';
